config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users

  root "static_pages#home"	
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/info', to: 'static_pages#info'
  get '/vr_ar', to: 'static_pages#vr_ar'
  get '/ai', to: 'static_pages#ai'
  get '/sec', to: 'static_pages#security'

  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'

  resources :account_activations, only: [:edit] 
  resources :microposts,          only: [:create, :destroy]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  @@dailySentence=nil
  @@now_day=nil
  def home
    url = 'http://www.dailyenglishquote.com/?variant=zh-hans'
    re_first = '<div class="post-info-top cf">'
    re_second = '<div class="at-below-post-homepage'

    if @@dailySentence&&@@now_day==Time.now.day
    else
      @@dailySentence = (get_sentence(url,re_first,re_second)+"</div>").force_encoding("UTF-8")
      @@now_day=Time.now.day      
    end
    @dailySentence=@@dailySentence
    
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def about
  end

  @@infoNews=nil
  @@now_hour=nil
  def info
    if @@infoNews&&@@now_hour==Time.now.hour
    else
      @@infoNews = get_infoq().force_encoding("UTF-8")
      @@now_hour=Time.now.hour      
    end
    @infoNews=@@infoNews    
  end

  @@VR=nil
  @@hour_getVR=nil
  def vr_ar
    url = 'http://www.leiphone.com/category/arvr'
    re_first = '<div class="list">'
    re_second = '<div class="lph-page">'
    if @@VR&&@@hour_getVR==Time.now.hour
    else
      @@VR = get_sentence(url,re_first,re_second).force_encoding("UTF-8")
      @@VR.gsub!('<div class="img">','<div class="img" style="display:none">')  
      @@hour_getVR=Time.now.hour  
    end
      @VR=@@VR
  end

  @@AI=nil
  @@hour_getAI=nil
  def ai
    url = 'http://www.leiphone.com/category/ai'
    re_first = '<div class="list">'
    re_second = '<div class="lph-page">'
    if @@AI&&@@hour_getAI==Time.now.hour
    else
      @@AI = get_sentence(url,re_first,re_second).force_encoding("UTF-8")
      @@AI.gsub!('<div class="img">','<div class="img" style="display:none">')  
      @@hour_getAI=Time.now.hour 
    end
      @AI=@@AI
  end

  @@sec=nil
  @@day_getSec=nil
  def security
    url = 'http://www.leiphone.com/category/letshome'
    re_first = '<div class="list">'
    re_second = '<div class="lph-page">'
    if @@sec&&@@day_getSec==Time.now.day
    else
      @@sec = get_sentence(url,re_first,re_second).force_encoding("UTF-8")
      @@sec.gsub!('<div class="img">','<div class="img" style="display:none">')  
      @@day_getSec=Time.now.day 
    end
      @sec=@@sec
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/views/static_pages/_nav-tabs.html.erb
<ul class="nav nav-tabs">
	<li><%= link_to "Infor",   info_path %></li>
	<li><%= link_to "VR/AR", vr_ar_path %></li>
	<li><%= link_to "AI", ai_path %></li>
	<li><%= link_to "Security", sec_path %></li>
</ul>

app/views/static_pages/about.html.erb
<% provide(:title,"About") %>

<div class="jumbotron">
    <h2 class="hahafont">This is HaHaGo, just developing, and will be more fun and useful. Thanks for your coming.   
    </h2>
    <center>>^_^<</center>
    <br>
    shangchen.chang@aliyun.com
</div>

app/views/static_pages/ai.html.erb
<% provide(:title,"AI") %>
<%= render 'nav-tabs' %>
<div class="jumbotron">
  <p class="hahafont text-left">AI:</p>
  <hr>
    <%= raw(@AI) %> 
</div>

app/views/static_pages/home.html.erb
<% provide(:title,"Home") %>
<div class="center jumbotron">
    <%= raw(@dailySentence) %> 

<% if !logged_in? %>
  <hr>
  <p class="hahafont">Welcome to the HaHaGo</p>


  <%= link_to "Infor", info_path, class: "btn btn-lg btn-primary" %>
<% end %>
 
    
</div>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
     <div class="col-md-8">
      <h3>Microposts</h3>
      <%= render 'shared/feed' %>
    </div>   
  </div>
<% end %>

app/views/static_pages/info.html.erb
<% provide(:title,"Infor") %>
<%= render 'nav-tabs' %>
<div class="jumbotron">
  <p class="hahafont text-left">IT news:</p>
  <hr>
    <%= raw(@infoNews) %> 
</div>

app/views/static_pages/security.html.erb
<% provide(:title,"Security") %>
<%= render 'nav-tabs' %>
<div class="jumbotron">
  <p class="hahafont text-left">Security:</p>
  <hr>
    <%= raw(@sec) %> 
</div>

app/views/static_pages/vr_ar.html.erb
<% provide(:title, "VR/AR") %>
<%= render 'nav-tabs' %>
<div class="jumbotron">
  <p class="hahafont text-left">VR/AR:</p>
  <hr>
    <%= raw(@VR) %> 
</div>