config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users

  root "static_pages#home"	
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/info', to: 'static_pages#info'
  get '/vr_ar', to: 'static_pages#vr_ar'
  get '/ai', to: 'static_pages#ai'
  get '/sec', to: 'static_pages#security'

  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'

  resources :account_activations, only: [:edit] 
  resources :microposts,          only: [:create, :destroy]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
<div class="container">
  <small>
    made by Niko
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home",   home_path %></li>
      <li><%= link_to "About",   about_path %></li>
    </ul>
  </nav>
 </div> 
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "HAHAGO", root_path, id: "logo" %>

      <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse"
          data-target="#example-navbar-collapse">
      <span class="sr-only">切换导航</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      </div>

     <div class="collapse navbar-collapse" id="example-navbar-collapse">

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Info",   info_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
      </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0" />
  <meta name="keywords" content="AR,VR,AI">
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>   
  </head>

  <body>
  <%= render 'layouts/header'%>
  <div class="container">
        <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> hahafont"><%= message %></div>
        <% end %>
    <%= yield %>
    <!--<%= debug(params) %>-->
    <br>
    <%= render 'layouts/footer' %>
  </div>
  <script type="text/javascript">
      ga('create', 'UA-49507355-2', 'auto');
      ga('send', 'pageview');  
   </script>   
  </body>
</html>